#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module ChocolateAdditionsType
  ALMONDS = 1
  NOUGAT = 2
  HAIR = 3
  VALUE_MAP = {1 => "ALMONDS", 2 => "NOUGAT", 3 => "HAIR"}
  VALID_VALUES = Set.new([ALMONDS, NOUGAT, HAIR]).freeze
end

