#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Composite
  include ::Thrift::Struct, ::Thrift::Struct_Union
  MAP_OF_MAPS = 1
  MAP_OF_SETS = 2
  MAP_OF_LISTS = 3
  SET_OF_MAPS = 4
  SET_OF_SETS = 5
  SET_OF_LISTS = 6
  LIST_OF_MAPS = 7
  LIST_OF_SETS = 8
  LIST_OF_LISTS = 9

  FIELDS = {
    MAP_OF_MAPS => {:type => ::Thrift::Types::MAP, :name => 'map_of_maps', :key => {:type => ::Thrift::Types::MAP, :key => {:type => ::Thrift::Types::BYTE}, :value => {:type => ::Thrift::Types::BYTE}}, :value => {:type => ::Thrift::Types::MAP, :key => {:type => ::Thrift::Types::BYTE}, :value => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    MAP_OF_SETS => {:type => ::Thrift::Types::MAP, :name => 'map_of_sets', :key => {:type => ::Thrift::Types::SET, :element => {:type => ::Thrift::Types::BYTE}}, :value => {:type => ::Thrift::Types::SET, :element => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    MAP_OF_LISTS => {:type => ::Thrift::Types::MAP, :name => 'map_of_lists', :key => {:type => ::Thrift::Types::LIST, :element => {:type => ::Thrift::Types::BYTE}}, :value => {:type => ::Thrift::Types::LIST, :element => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    SET_OF_MAPS => {:type => ::Thrift::Types::SET, :name => 'set_of_maps', :element => {:type => ::Thrift::Types::MAP, :key => {:type => ::Thrift::Types::BYTE}, :value => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    SET_OF_SETS => {:type => ::Thrift::Types::SET, :name => 'set_of_sets', :element => {:type => ::Thrift::Types::SET, :element => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    SET_OF_LISTS => {:type => ::Thrift::Types::SET, :name => 'set_of_lists', :element => {:type => ::Thrift::Types::LIST, :element => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    LIST_OF_MAPS => {:type => ::Thrift::Types::LIST, :name => 'list_of_maps', :element => {:type => ::Thrift::Types::MAP, :key => {:type => ::Thrift::Types::BYTE}, :value => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    LIST_OF_SETS => {:type => ::Thrift::Types::LIST, :name => 'list_of_sets', :element => {:type => ::Thrift::Types::SET, :element => {:type => ::Thrift::Types::BYTE}}, :optional => true},
    LIST_OF_LISTS => {:type => ::Thrift::Types::LIST, :name => 'list_of_lists', :element => {:type => ::Thrift::Types::LIST, :element => {:type => ::Thrift::Types::BYTE}}, :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

