#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Ex < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  MESSAGE = 1
  NUM = 99

  FIELDS = {
    MESSAGE => {:type => ::Thrift::Types::STRING, :name => 'message', :optional => true},
    NUM => {:type => ::Thrift::Types::BYTE, :name => 'num', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Ex2 < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ERROR_CODE = 1

  FIELDS = {
    ERROR_CODE => {:type => ::Thrift::Types::I16, :name => 'error_code', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  VAL = 1
  VAL_MAP = 2
  VAL_SET = 3
  VAL_LIST = 4

  FIELDS = {
    VAL => {:type => ::Thrift::Types::STRUCT, :name => 'val', :class => ::Ex, :optional => true},
    VAL_MAP => {:type => ::Thrift::Types::MAP, :name => 'val_map', :key => {:type => ::Thrift::Types::STRUCT, :class => ::Ex}, :value => {:type => ::Thrift::Types::STRUCT, :class => ::Ex}, :optional => true},
    VAL_SET => {:type => ::Thrift::Types::SET, :name => 'val_set', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Ex}, :optional => true},
    VAL_LIST => {:type => ::Thrift::Types::LIST, :name => 'val_list', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Ex}, :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

