#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Multifield
  include ::Thrift::Struct, ::Thrift::Struct_Union
  BOOL_ONE = 1
  BOOL_TWO = 2
  BOOL_THREE = 3
  MAP_FOUR = 4
  LIST_FIVE = 5
  BYTE_SIX = 6
  BOOL_SEVENTEEN = 17

  FIELDS = {
    BOOL_ONE => {:type => ::Thrift::Types::BOOL, :name => 'bool_one', :optional => true},
    BOOL_TWO => {:type => ::Thrift::Types::BOOL, :name => 'bool_two', :optional => true},
    BOOL_THREE => {:type => ::Thrift::Types::BOOL, :name => 'bool_three', :optional => true},
    MAP_FOUR => {:type => ::Thrift::Types::MAP, :name => 'map_four', :key => {:type => ::Thrift::Types::BOOL}, :value => {:type => ::Thrift::Types::BOOL}, :optional => true},
    LIST_FIVE => {:type => ::Thrift::Types::LIST, :name => 'list_five', :element => {:type => ::Thrift::Types::BOOL}, :optional => true},
    BYTE_SIX => {:type => ::Thrift::Types::BYTE, :name => 'byte_six', :optional => true},
    BOOL_SEVENTEEN => {:type => ::Thrift::Types::BOOL, :name => 'bool_seventeen', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

