#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Typedefs
  include ::Thrift::Struct, ::Thrift::Struct_Union
  INTS = 1
  MAPPINGS = 2
  NUMBERS = 3

  FIELDS = {
    INTS => {:type => ::Thrift::Types::SET, :name => 'ints', :element => {:type => ::Thrift::Types::I32}, :optional => true},
    MAPPINGS => {:type => ::Thrift::Types::MAP, :name => 'mappings', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}, :optional => true},
    NUMBERS => {:type => ::Thrift::Types::LIST, :name => 'numbers', :element => {:type => ::Thrift::Types::I64}, :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

