#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class StructValue
  include ::Thrift::Struct, ::Thrift::Struct_Union
  USERNAME = 1

  FIELDS = {
    USERNAME => {:type => ::Thrift::Types::STRING, :name => 'username', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

class Union < ::Thrift::Union
  include ::Thrift::Struct_Union
  class << self
    def int_field(val)
      Union.new(:int_field, val)
    end

    def struct_field(val)
      Union.new(:struct_field, val)
    end

    def string_field(val)
      Union.new(:string_field, val)
    end

    def list_field(val)
      Union.new(:list_field, val)
    end
  end

  INT_FIELD = 1
  STRUCT_FIELD = 2
  STRING_FIELD = 3
  LIST_FIELD = 4

  FIELDS = {
    INT_FIELD => {:type => ::Thrift::Types::I64, :name => 'int_field', :optional => true},
    STRUCT_FIELD => {:type => ::Thrift::Types::STRUCT, :name => 'struct_field', :class => ::StructValue, :optional => true},
    STRING_FIELD => {:type => ::Thrift::Types::STRING, :name => 'string_field', :optional => true},
    LIST_FIELD => {:type => ::Thrift::Types::LIST, :name => 'list_field', :element => {:type => ::Thrift::Types::I16}, :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
    raise(StandardError, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
  end

  ::Thrift::Union.generate_accessors self
end

class UStruct
  include ::Thrift::Struct, ::Thrift::Struct_Union
  MY_UNION = 1
  U_MAP = 2
  U_SET = 3
  U_LIST = 4

  FIELDS = {
    MY_UNION => {:type => ::Thrift::Types::STRUCT, :name => 'my_union', :class => ::Union, :optional => true},
    U_MAP => {:type => ::Thrift::Types::MAP, :name => 'u_map', :key => {:type => ::Thrift::Types::STRUCT, :class => ::Union}, :value => {:type => ::Thrift::Types::STRUCT, :class => ::Union}, :optional => true},
    U_SET => {:type => ::Thrift::Types::SET, :name => 'u_set', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Union}, :optional => true},
    U_LIST => {:type => ::Thrift::Types::LIST, :name => 'u_list', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Union}, :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

