#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'x_man_types'

EARTH_616 = %q"Earth-616"

Wolverine = ::XMan.new({
  %q"handle" => %q"Wolverine",
  %q"name" => %q"Logan",
  %q"power_level" =>   1,
})

Cyclops = ::XMan.new({
  %q"handle" => %q"Cyclops",
  %q"name" => %q"Scott Summers",
  %q"power_level" =>   1,
})

Storm = ::XMan.new({
  %q"handle" => %q"Storm",
  %q"name" => %q"Ororo Monroe",
  %q"power_level" =>   0,
})

Phoenix = ::XMan.new({
  %q"handle" => %q"Phoenix",
  %q"name" => %q"Jean Grey",
  %q"power_level" =>   2,
})

