#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys
from .ttypes import *
EARTH_616 = "Earth-616"
Wolverine = XMan(**{
    "handle": "Wolverine",
    "name": "Logan",
    "power_level": 1,
})
Cyclops = XMan(**{
    "handle": "Cyclops",
    "name": "Scott Summers",
    "power_level": 1,
})
Storm = XMan(**{
    "handle": "Storm",
    "name": "Ororo Monroe",
    "power_level": 0,
})
Phoenix = XMan(**{
    "handle": "Phoenix",
    "name": "Jean Grey",
    "power_level": 2,
})
